modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/ArkTechMC/Jupiter/issues"
license = "GNU LGPL 3.0"

[[mods]]
modId = "jupiter"
version = "${version}"
displayName = "Jupiter"
authors = "IAFEnvoy"
description = '''
A powerful, auto sync config library.
'''
logoFile = "logo.jpg"

[[dependencies.jupiter]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jupiter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,1.17)"
ordering = "NONE"
side = "BOTH"
